# Usa una imagen ligera de Node.js
FROM node:20-alpine

# Crea el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del proyecto (esto incluye Vite)
RUN npm install

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto 5173 para Vite
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo de Vite
CMD ["npm", "run", "dev"]
