# Usa una imagen de Node.js
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del backend
RUN npm install

# Copia todo el código fuente del backend
COPY . .

# Copia el script wait-for-it.sh
COPY wait-for-it.sh /usr/src/app/wait-for-it.sh
RUN chmod +x /usr/src/app/wait-for-it.sh

# Expone el puerto 3000
EXPOSE 3000

# Usa el script wait-for-it.sh para esperar que PostgreSQL esté listo
CMD ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]

